import { ParsedMessage } from '../types';

export interface ParseResult {
  title: string;
  generatedBy?: string;
  generationDate?: string;
  participants: string[];
  messages: ParsedMessage[];
  error?: string;
}

/**
 * Fixes common Facebook UTF-8 / Latin-1 mojibake encoding issues (e.g. Ã¤ -> ä, Ãµ -> õ)
 */
export function fixMojibake(text: string): string {
  if (!text) return '';
  // Check if string contains typical UTF-8 misinterpreted as Windows-1252/Latin-1 characters
  if (/[\u00C0-\u00FF][\u0080-\u00BF]/.test(text)) {
    try {
      const bytes = new Uint8Array(text.length);
      for (let i = 0; i < text.length; i++) {
        bytes[i] = text.charCodeAt(i) & 0xff;
      }
      const decoded = new TextDecoder('utf-8', { fatal: false }).decode(bytes);
      if (decoded && !decoded.includes('')) {
        return decoded;
      }
    } catch {
      // Return original if decoding fails
    }
  }
  return text;
}

/**
 * Robust date parser for multiple Facebook export timestamp formats:
 * - "Feb 01, 2024 12:58:07 pm"
 * - "Feb 1, 2024, 12:58:07 PM"
 * - "06.04.2021 03:40:32"
 * - "2021-04-06 03:40:32"
 * - "Monday, January 26, 2026 at 2:45 AM UTC+02:00"
 * - "Apr 6, 2021 3:40am"
 */
export function parseFacebookTimestamp(dateStr: string): Date | null {
  if (!dateStr) return null;
  const cleanStr = dateStr.trim();

  // Try standard Date.parse first
  const standardDate = new Date(cleanStr);
  if (!isNaN(standardDate.getTime())) {
    return standardDate;
  }

  // Pattern: "Feb 01, 2024 12:58:07 pm" or "Feb 1, 2024 12:58:07 pm"
  const fbMonthPattern = /^([A-Za-z]{3,9})\s+(\d{1,2}),?\s+(\d{4}),?\s+(\d{1,2}):(\d{2})(?::(\d{2}))?\s*(am|pm)?/i;
  const matchMonth = cleanStr.match(fbMonthPattern);
  if (matchMonth) {
    const [, monthStr, dayStr, yearStr, hourStr, minStr, secStr, ampm] = matchMonth;
    const months: Record<string, number> = {
      jan: 0, january: 0, feb: 1, february: 1, mar: 2, march: 2, apr: 3, april: 3,
      may: 4, jun: 5, june: 5, jul: 6, july: 6, aug: 7, august: 7, sep: 8, september: 8,
      oct: 9, october: 9, nov: 10, november: 10, dec: 11, december: 11
    };
    const month = months[monthStr.toLowerCase()] ?? 0;
    const day = parseInt(dayStr, 10);
    const year = parseInt(yearStr, 10);
    let hour = parseInt(hourStr, 10);
    const min = parseInt(minStr, 10);
    const sec = secStr ? parseInt(secStr, 10) : 0;

    if (ampm) {
      const isPm = ampm.toLowerCase() === 'pm';
      if (isPm && hour < 12) hour += 12;
      if (!isPm && hour === 12) hour = 0;
    }

    const d = new Date(year, month, day, hour, min, sec);
    if (!isNaN(d.getTime())) return d;
  }

  // Pattern: DD.MM.YYYY HH:mm:ss
  const dotPattern = /^(\d{1,2})\.(\d{1,2})\.(\d{4})\s+(\d{1,2}):(\d{2})(?::(\d{2}))?/;
  const matchDot = cleanStr.match(dotPattern);
  if (matchDot) {
    const [, dayStr, monthStr, yearStr, hourStr, minStr, secStr] = matchDot;
    const d = new Date(
      parseInt(yearStr, 10),
      parseInt(monthStr, 10) - 1,
      parseInt(dayStr, 10),
      parseInt(hourStr, 10),
      parseInt(minStr, 10),
      secStr ? parseInt(secStr, 10) : 0
    );
    if (!isNaN(d.getTime())) return d;
  }

  return null;
}

/**
 * Parses a Facebook Messenger HTML export file into structured data
 */
export function parseMessengerHTML(htmlContent: string, fileName: string, partNumber: number): ParseResult {
  try {
    const parser = new DOMParser();
    const doc = parser.parseFromString(htmlContent, 'text/html');

    // 1. Extract Conversation Title
    let title = '';
    const titleElem = doc.querySelector('title');
    if (titleElem && titleElem.textContent) {
      title = fixMojibake(titleElem.textContent.trim());
    }

    // Check header elements for conversation name
    const headerTitle = doc.querySelector('._a6-h, h1, ._2ph_, header, div[role="main"] > div:first-child');
    if (!title && headerTitle && headerTitle.textContent) {
      title = fixMojibake(headerTitle.textContent.trim());
    }

    // 2. Extract "Generated by..." info if present
    let generatedBy: string | undefined;
    let generationDate: string | undefined;
    const bodyText = doc.body.textContent || '';
    const genMatch = bodyText.match(/Generated by\s+(.+?)\s+on\s+([A-Za-z]+,\s+[A-Za-z]+\s+\d{1,2},\s+\d{4}\s+at\s+[\d:]+\s+[A-Za-z0-9:+]+)/i);
    if (genMatch) {
      generatedBy = fixMojibake(genMatch[1].trim());
      generationDate = fixMojibake(genMatch[2].trim());
    }

    // 3. Find Message Elements
    // Facebook exports use various classes across different export versions:
    // Format A (Modern Meta): ._a6-g
    // Format B (Standard): .pam._3-95._2pi0._2lef or ._3-96
    // Format C (Generic): .message-item, .chat-message, or generic div blocks inside role="main"
    let messageElements = Array.from(doc.querySelectorAll('._a6-g, .pam._3-95, ._2let, ._3-95._2pi0'));
    
    if (messageElements.length === 0) {
      // Fallback: look for container cards or repeating sibling structures
      const possibleContainers = Array.from(doc.querySelectorAll('div[role="main"] > div, body > div > div, .uiBoxWhite'));
      if (possibleContainers.length > 2) {
        messageElements = possibleContainers.filter(el => {
          const text = el.textContent || '';
          return text.length > 5 && /\d{4}/.test(text); // has year/timestamp
        });
      }
    }

    const participantsSet = new Set<string>();
    const messages: ParsedMessage[] = [];

    messageElements.forEach((el, index) => {
      // Extract Sender
      let sender = '';
      const senderElem = el.querySelector('._2ph_, ._a6-h, ._a6-i, strong, h3, ._3-96._2pio');
      if (senderElem && senderElem.textContent) {
        sender = fixMojibake(senderElem.textContent.trim());
      } else {
        // Fallback: first text node or bold element
        const firstDiv = el.querySelector('div');
        if (firstDiv && firstDiv.textContent) {
          const lines = firstDiv.textContent.trim().split('\n');
          if (lines[0]) sender = fixMojibake(lines[0].trim());
        }
      }

      // Extract Timestamp
      let rawTimestamp = '';
      const timeElem = el.querySelector('._a6-o, ._3-94, ._2lem, .timestamp, time');
      if (timeElem && timeElem.textContent) {
        rawTimestamp = timeElem.textContent.trim();
      } else {
        // Look for timestamp pattern in element text
        const text = el.textContent || '';
        const dateMatch = text.match(/(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]* \d{1,2},? \d{4}[\s\d:apmAPM,]+/i);
        if (dateMatch) {
          rawTimestamp = dateMatch[0].trim();
        }
      }

      const timestamp = parseFacebookTimestamp(rawTimestamp);

      // Extract Content / Text
      let content = '';
      const contentElem = el.querySelector('._a6-p, ._3-96:not(._2pio), ._2lek, ._2lel, p');
      if (contentElem && contentElem.textContent) {
        content = fixMojibake(contentElem.textContent.trim());
      } else {
        // Collect text excluding sender and time
        const clone = el.cloneNode(true) as HTMLElement;
        if (senderElem) {
          const s = clone.querySelector('._2ph_, ._a6-h, strong, h3');
          s?.remove();
        }
        if (timeElem) {
          const t = clone.querySelector('._a6-o, ._3-94, ._2lem, .timestamp');
          t?.remove();
        }
        content = fixMojibake(clone.textContent?.trim() || '');
      }

      // Extract Photos
      const photos: string[] = [];
      const imgElements = el.querySelectorAll('img');
      imgElements.forEach(img => {
        const src = img.getAttribute('src') || '';
        const alt = img.getAttribute('alt') || '';
        // Skip avatar or UI icons if detected
        if (src && !src.includes('avatar') && !src.includes('icon')) {
          photos.push(src);
        } else if (alt) {
          photos.push(alt);
        }
      });

      // Extract Audio / Voice notes
      const audio: string[] = [];
      const audioElements = el.querySelectorAll('audio, a[href*=".mp4"], a[href*=".aac"], a[href*=".mp3"]');
      audioElements.forEach(aud => {
        const src = (aud as HTMLAnchorElement).href || aud.getAttribute('src') || 'Audio File';
        audio.push(src);
      });

      // Extract Reactions
      const reactions: { reaction: string; actor: string }[] = [];
      const reactionElements = el.querySelectorAll('._a6-q li, ._a6-q, ul._a6-q > li, .reactions li');
      if (reactionElements.length > 0) {
        reactionElements.forEach(r => {
          const rText = fixMojibake(r.textContent?.trim() || '');
          if (rText) {
            // e.g. "🥰Marianne Carmen Perli" or "❤️ John"
            const emojiMatch = rText.match(/^(\p{Emoji}+|\S+)\s*(.*)$/u);
            if (emojiMatch) {
              reactions.push({
                reaction: emojiMatch[1],
                actor: emojiMatch[2] || sender,
              });
            } else {
              reactions.push({ reaction: '👍', actor: rText });
            }
          }
        });
      } else {
        // Check inline text reactions like "(Reactions: 🥰Marianne Carmen Perli)"
        const reactionMatch = content.match(/\(Reactions:\s*([^)]+)\)/i);
        if (reactionMatch) {
          const rText = reactionMatch[1].trim();
          reactions.push({ reaction: rText, actor: '' });
        }
      }

      // Check if this is a Call record
      const isCall = /missed (?:your )?call|video chat|call started|call ended|audio call/i.test(content);

      if (sender) {
        participantsSet.add(sender);
      }

      if (sender || content || photos.length > 0 || isCall) {
        messages.push({
          id: `${fileName}_msg_${index}_${timestamp?.getTime() || index}`,
          sender: sender || 'Unknown',
          timestamp,
          rawTimestamp,
          content,
          photos,
          videos: [],
          audio,
          stickers: [],
          reactions,
          isCall,
          sourceFile: fileName,
          sourcePartNumber: partNumber,
        });
      }
    });

    return {
      title: title || fileName.replace(/\.html?$/i, ''),
      generatedBy,
      generationDate,
      participants: Array.from(participantsSet),
      messages,
    };
  } catch (err: unknown) {
    const errorMsg = err instanceof Error ? err.message : String(err);
    return {
      title: fileName,
      participants: [],
      messages: [],
      error: errorMsg,
    };
  }
}
