import { RawFile } from '../types';

export const SAMPLE_FILES: RawFile[] = [
  // -------------------------------------------------------------
  // THREAD 1: Marianne Carmen Perli & Madis Lemberk (Part 1 - Recent)
  // -------------------------------------------------------------
  {
    name: 'mariannecarmenperli_3818328304870619_message_1.html',
    path: 'messages/inbox/mariannecarmenperli_3818328304870619/message_1.html',
    size: 24500,
    content: `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Marianne Carmen Perli</title>
</head>
<body>
  <div role="main">
    <div class="_a6-h _a6-i">
      <h1>Marianne Carmen Perli</h1>
      <div>Generated by Madis Lemberk on Monday, January 26, 2026 at 2:45 AM UTC+02:00</div>
    </div>
    
    <div class="_a6-g">
      <div class="_2ph_ _a6-h _a6-i">Madis Lemberk</div>
      <div class="_a6-o">Feb 03, 2024 11:23:04 am</div>
      <div class="_a6-p">📷 <img src="photo_001.jpg" alt="[Photo]" /></div>
    </div>

    <div class="_a6-g">
      <div class="_2ph_ _a6-h _a6-i">Madis Lemberk</div>
      <div class="_a6-o">Feb 01, 2024 12:58:07 pm</div>
      <div class="_a6-p">woo missed your call.</div>
    </div>

    <div class="_a6-g">
      <div class="_2ph_ _a6-h _a6-i">Madis Lemberk</div>
      <div class="_a6-o">Feb 01, 2024 12:57:37 pm</div>
      <div class="_a6-p">Võtan veel poesy midagi v</div>
    </div>

    <div class="_a6-g">
      <div class="_2ph_ _a6-h _a6-i">Marianne Carmen Perli</div>
      <div class="_a6-o">Feb 01, 2024 12:57:10 pm</div>
      <div class="_a6-p">Igakord tuleb nüüd igaks juhuks teha</div>
    </div>

    <div class="_a6-g">
      <div class="_2ph_ _a6-h _a6-i">Marianne Carmen Perli</div>
      <div class="_a6-o">Feb 01, 2024 12:56:42 pm</div>
      <div class="_a6-p">Mhmm</div>
    </div>

    <div class="_a6-g">
      <div class="_2ph_ _a6-h _a6-i">Madis Lemberk</div>
      <div class="_a6-o">Feb 01, 2024 12:56:31 pm</div>
      <div class="_a6-p">Et ei pannud</div>
    </div>
  </div>
</body>
</html>`
  },

  // -------------------------------------------------------------
  // THREAD 1: Marianne Carmen Perli & Madis Lemberk (Part 2 - Middle)
  // -------------------------------------------------------------
  {
    name: 'mariannecarmenperli_3818328304870619_message_2.html',
    path: 'messages/inbox/mariannecarmenperli_3818328304870619/message_2.html',
    size: 28400,
    content: `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Marianne Carmen Perli</title>
</head>
<body>
  <div role="main">
    <div class="_a6-h _a6-i">
      <h1>Marianne Carmen Perli</h1>
      <div>Generated by Madis Lemberk on Monday, January 26, 2026 at 2:45 AM UTC+02:00</div>
    </div>

    <div class="_a6-g">
      <div class="_2ph_ _a6-h _a6-i">Marianne Carmen Perli</div>
      <div class="_a6-o">Apr 06, 2021 03:40:32 am</div>
      <div class="_a6-p">Tsss</div>
    </div>

    <div class="_a6-g">
      <div class="_2ph_ _a6-h _a6-i">Madis Lemberk</div>
      <div class="_a6-o">Apr 06, 2021 03:43:27 am</div>
      <div class="_a6-p">Ooooh no</div>
    </div>

    <div class="_a6-g">
      <div class="_2ph_ _a6-h _a6-i">Madis Lemberk</div>
      <div class="_a6-o">Apr 06, 2021 03:43:57 am</div>
      <div class="_a6-p">Palj jalutd oli</div>
    </div>

    <div class="_a6-g">
      <div class="_2ph_ _a6-h _a6-i">Madis Lemberk</div>
      <div class="_a6-o">Apr 06, 2021 03:44:11 am</div>
      <div class="_a6-p">Kalamaja ju ümber nurga</div>
    </div>

    <div class="_a6-g">
      <div class="_2ph_ _a6-h _a6-i">Marianne Carmen Perli</div>
      <div class="_a6-o">Apr 06, 2021 03:44:22 am</div>
      <div class="_a6-p">Mingi 30 minta</div>
    </div>

    <div class="_a6-g">
      <div class="_2ph_ _a6-h _a6-i">Madis Lemberk</div>
      <div class="_a6-o">Apr 06, 2021 03:46:37 am</div>
      <div class="_a6-p">Improsae et konsraioonia viits jäid Aiaiximp</div>
    </div>

    <div class="_a6-g">
      <div class="_2ph_ _a6-h _a6-i">Madis Lemberk</div>
      <div class="_a6-o">Apr 06, 2021 03:47:03 am</div>
      <div class="_a6-p">Tr .</div>
    </div>

    <div class="_a6-g">
      <div class="_2ph_ _a6-h _a6-i">Madis Lemberk</div>
      <div class="_a6-o">Apr 06, 2021 03:47:20 am</div>
      <div class="_a6-p">Mu klavi huiab haha</div>
    </div>

    <div class="_a6-g">
      <div class="_2ph_ _a6-h _a6-i">Madis Lemberk</div>
      <div class="_a6-o">Apr 06, 2021 03:48:52 am</div>
      <div class="_a6-p">Impressev et viitsid keaetööd</div>
    </div>

    <div class="_a6-g">
      <div class="_2ph_ _a6-h _a6-i">Marianne Carmen Perli</div>
      <div class="_a6-o">Apr 06, 2021 03:49:15 am</div>
      <div class="_a6-p">Bahahaha</div>
    </div>

    <div class="_a6-g">
      <div class="_2ph_ _a6-h _a6-i">Marianne Carmen Perli</div>
      <div class="_a6-o">Apr 06, 2021 03:49:52 am</div>
      <div class="_a6-p">Mdea kuidagi täna kodu kutsus</div>
    </div>

    <div class="_a6-g">
      <div class="_2ph_ _a6-h _a6-i">Marianne Carmen Perli</div>
      <div class="_a6-o">Apr 06, 2021 03:50:50 am</div>
      <div class="_a6-p">Ega ma poole tee pealt mõtlesin et ma kõnnin tagasi ka haha</div>
    </div>

    <div class="_a6-g">
      <div class="_2ph_ _a6-h _a6-i">Marianne Carmen Perli</div>
      <div class="_a6-o">Apr 06, 2021 04:08:23 am</div>
      <div class="_a6-p">Head ööd madis</div>
    </div>
  </div>
</body>
</html>`
  },

  // -------------------------------------------------------------
  // THREAD 1: Marianne Carmen Perli & Madis Lemberk (Part 3 - Morning)
  // -------------------------------------------------------------
  {
    name: 'mariannecarmenperli_3818328304870619_message_3.html',
    path: 'messages/inbox/mariannecarmenperli_3818328304870619/message_3.html',
    size: 32100,
    content: `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Marianne Carmen Perli</title>
</head>
<body>
  <div role="main">
    <div class="_a6-h _a6-i">
      <h1>Marianne Carmen Perli</h1>
      <div>Generated by Madis Lemberk on Monday, January 26, 2026 at 2:45 AM UTC+02:00</div>
    </div>

    <div class="_a6-g">
      <div class="_2ph_ _a6-h _a6-i">Madis Lemberk</div>
      <div class="_a6-o">Apr 06, 2021 09:29:47 am</div>
      <div class="_a6-p">And a good morning 🌄</div>
    </div>

    <div class="_a6-g">
      <div class="_2ph_ _a6-h _a6-i">Marianne Carmen Perli</div>
      <div class="_a6-o">Apr 06, 2021 12:43:18 pm</div>
      <div class="_a6-p">Good morning jahh</div>
    </div>

    <div class="_a6-g">
      <div class="_2ph_ _a6-h _a6-i">Madis Lemberk</div>
      <div class="_a6-o">Apr 06, 2021 01:32:18 pm</div>
      <div class="_a6-p">Rise and shine</div>
    </div>

    <div class="_a6-g">
      <div class="_2ph_ _a6-h _a6-i">Marianne Carmen Perli</div>
      <div class="_a6-o">Apr 06, 2021 01:36:20 pm</div>
      <div class="_a6-p">Haha peaks aga ma üldse ei viitsi</div>
    </div>

    <div class="_a6-g">
      <div class="_2ph_ _a6-h _a6-i">Madis Lemberk</div>
      <div class="_a6-o">Apr 06, 2021 01:40:58 pm</div>
      <div class="_a6-p">Jep mul kohe naptime tulemas</div>
    </div>

    <div class="_a6-g">
      <div class="_2ph_ _a6-h _a6-i">Madis Lemberk</div>
      <div class="_a6-o">Apr 06, 2021 01:41:40 pm</div>
      <div class="_a6-p">Loeng i can barely keep my eyes open</div>
    </div>

    <div class="_a6-g">
      <div class="_2ph_ _a6-h _a6-i">Madis Lemberk</div>
      <div class="_a6-o">Apr 06, 2021 01:41:45 pm</div>
      <div class="_a6-p"><img src="photo_nap.jpg" alt="[Photo]" /></div>
      <ul class="_a6-q">
        <li>🥰Marianne Carmen Perli</li>
      </ul>
    </div>

    <div class="_a6-g">
      <div class="_2ph_ _a6-h _a6-i">Marianne Carmen Perli</div>
      <div class="_a6-o">Apr 06, 2021 01:42:22 pm</div>
      <div class="_a6-p">Hahah see on mu lemmik asi rn</div>
    </div>

    <div class="_a6-g">
      <div class="_2ph_ _a6-h _a6-i">Marianne Carmen Perli</div>
      <div class="_a6-o">Apr 06, 2021 01:42:51 pm</div>
      <div class="_a6-p">Ma pean koerale mingit rohtu minema ostma</div>
    </div>

    <div class="_a6-g">
      <div class="_2ph_ _a6-h _a6-i">Madis Lemberk</div>
      <div class="_a6-o">Apr 06, 2021 01:44:49 pm</div>
      <div class="_a6-p">Suht uimane</div>
    </div>

    <div class="_a6-g">
      <div class="_2ph_ _a6-h _a6-i">Madis Lemberk</div>
      <div class="_a6-o">Apr 06, 2021 01:45:03 pm</div>
      <div class="_a6-p">Kuidas sul</div>
    </div>

    <div class="_a6-g">
      <div class="_2ph_ _a6-h _a6-i">Marianne Carmen Perli</div>
      <div class="_a6-o">Apr 06, 2021 01:47:06 pm</div>
      <div class="_a6-p">Mul suht okei</div>
    </div>

    <div class="_a6-g">
      <div class="_2ph_ _a6-h _a6-i">Marianne Carmen Perli</div>
      <div class="_a6-o">Apr 06, 2021 01:59:18 pm</div>
      <div class="_a6-p">Yesss</div>
    </div>
  </div>
</body>
</html>`
  },

  // -------------------------------------------------------------
  // THREAD 2: Tallinn Summer Trip Group (Part 1 & 2)
  // -------------------------------------------------------------
  {
    name: 'tallinn_summer_trip_group_message_1.html',
    path: 'messages/inbox/tallinn_summer_trip_group/message_1.html',
    size: 19800,
    content: `<!DOCTYPE html>
<html>
<head>
  <title>Tallinn Summer Trip 2024</title>
</head>
<body>
  <div class="pam _3-95 _2pi0 _2lef">
    <div class="_2ph_ _a6-h">Artur Tamm</div>
    <div class="_3-94 _2lem">Jun 14, 2024 10:15:00 am</div>
    <div class="_3-96 _2pio _2lek _2lel">Hey everyone! Did we finalize the ferry tickets to Helsinki?</div>
  </div>
  <div class="pam _3-95 _2pi0 _2lef">
    <div class="_2ph_ _a6-h">Liisa Kallas</div>
    <div class="_3-94 _2lem">Jun 14, 2024 10:18:30 am</div>
    <div class="_3-96 _2pio _2lek _2lel">Yes, booked the 9:30 AM Megastar boat on Saturday! 🚢</div>
  </div>
  <div class="pam _3-95 _2pi0 _2lef">
    <div class="_2ph_ _a6-h">Madis Lemberk</div>
    <div class="_3-94 _2lem">Jun 14, 2024 10:22:00 am</div>
    <div class="_3-96 _2pio _2lek _2lel">Super! I will bring the board games and camera gear.</div>
  </div>
</body>
</html>`
  },
  {
    name: 'tallinn_summer_trip_group_message_2.html',
    path: 'messages/inbox/tallinn_summer_trip_group/message_2.html',
    size: 16500,
    content: `<!DOCTYPE html>
<html>
<head>
  <title>Tallinn Summer Trip 2024</title>
</head>
<body>
  <div class="pam _3-95 _2pi0 _2lef">
    <div class="_2ph_ _a6-h">Artur Tamm</div>
    <div class="_3-94 _2lem">May 20, 2024 08:30:15 pm</div>
    <div class="_3-96 _2pio _2lek _2lel">Starting the planning thread for our midsummer weekend trip!</div>
  </div>
  <div class="pam _3-95 _2pi0 _2lef">
    <div class="_2ph_ _a6-h">Liisa Kallas</div>
    <div class="_3-94 _2lem">May 20, 2024 08:35:00 pm</div>
    <div class="_3-96 _2pio _2lek _2lel">Count me in! Saaremaa or Hiiumaa?</div>
  </div>
</body>
</html>`
  },

  // -------------------------------------------------------------
  // THREAD 3: Single part conversation: David Wilson
  // -------------------------------------------------------------
  {
    name: 'david_wilson_1928472910_message_1.html',
    path: 'messages/inbox/david_wilson_1928472910/message_1.html',
    size: 14200,
    content: `<!DOCTYPE html>
<html>
<head>
  <title>David Wilson</title>
</head>
<body>
  <div class="_a6-g">
    <div class="_2ph_ _a6-h">David Wilson</div>
    <div class="_a6-o">Jan 15, 2025 04:12:00 pm</div>
    <div class="_a6-p">Hey! Are you available for a quick sync regarding the API specs?</div>
  </div>
  <div class="_a6-g">
    <div class="_2ph_ _a6-h">Madis Lemberk</div>
    <div class="_a6-o">Jan 15, 2025 04:14:30 pm</div>
    <div class="_a6-p">Sure David, let's jump on a 15-min call.</div>
  </div>
</body>
</html>`
  }
];
